# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: #'self-hosted-machine'
  name: 'ubuntu-latest'
  
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'app/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pwd
      cd $(Build.SourcesDirectory)/app/target
      ls

- task: PowerShell@2
  displayName: 'Debug - Print Size - Root'
  enabled: false
  inputs:
    targetType: 'inline'
    script: '(Get-ChildItem "$(Build.SourcesDirectory)\.." -Force -Recurse | Measure-Object -Property Length -sum | Select-Object -ExpandProperty Sum)/1GB'
- task: CopyFiles@2
  inputs:
    Contents: '$(Build.SourcesDirectory)/app/target/*.jar' 
    TargetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'BuildArtifacts'
    publishLocation: Container 

- task: PowerShell@2
  displayName: 'Debug - Print Size - Root'
  enabled: false
  inputs:
    targetType: 'inline'
    script: '(Get-ChildItem "$(Build.SourcesDirectory)\.." -Force -Recurse | Measure-Object -Property Length -sum | Select-Object -ExpandProperty Sum)/1GB'
