# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-2019'
  
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'app/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       pwd
#       cd $(Build.SourcesDirectory)/app/target
#       ls
- task: PowerShell@2
  displayName: 'Debug - Print Size - Root'
  enabled: true #false
  inputs:
    targetType: 'inline'
    script: |
      Get-CimInstance -ClassName Win32_LogicalDisk
      '(Get-ChildItem "$(Build.SourcesDirectory)\.." -Force -Recurse | Measure-Object -Property Length -sum | Select-Object -ExpandProperty Sum)/1GB'
  continueOnError: true
# - task: CopyFiles@2
#   inputs:
#     Contents: '$(Build.SourcesDirectory)/app/target/*.jar' 
#     TargetFolder: $(Build.ArtifactStagingDirectory)
#     CleanTargetFolder: true
#     flattenFolders: true
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: $(Build.ArtifactStagingDirectory)
#     ArtifactName: 'BuildArtifacts'
#     publishLocation: Container 
- task: PowerShell@2
  displayName: 'Debug - Print Size - Root'
  enabled: true #false
  inputs:
    targetType: 'inline'
    script: |
      'Get-CimInstance -ClassName Win32_LogicalDisk'
      Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object -Property DeviceID,FreeSpace
      Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object -Property DeviceID,@{'Name' = 'FreeSpace (GB)'; Expression= { [int]($_.FreeSpace / 1GB) }}
      Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object -Property DeviceID,@{'Name' = 'FreeSpace (GB)'; Expression= { [int]($_.FreeSpace / 1GB) }} | Measure-Object -Property 'FreeSpace (GB)' -Sum
      '(Get-ChildItem "$(Build.SourcesDirectory)\.." -Force -Recurse | Measure-Object -Property Length -sum | Select-Object -ExpandProperty Sum)/1GB'
- task: CmdLine@2
  inputs:
    script: |
      df -h
      'Get-CimInstance -ClassName Win32_LogicalDisk'
      Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object -Property DeviceID,FreeSpace
      Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object -Property DeviceID,@{'Name' = 'FreeSpace (GB)'; Expression= { [int]($_.FreeSpace / 1GB) }}
      Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object -Property DeviceID,@{'Name' = 'FreeSpace (GB)'; Expression= { [int]($_.FreeSpace / 1GB) }} | Measure-Object -Property 'FreeSpace (GB)' -Sum
    